// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
//
// To change the Firebase project, use the 'Update Firebase Project' action.
export const firebaseConfig = {
  apiKey: "REDACTED",
  authDomain: "REDACTED",
  projectId: "REDACTED",
  storageBucket: "REDACTED",
  messagingSenderId: "REDACTED",
  appId: "REDACTED",
};
